code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension esbenp.prettier-vscode
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ow.vscode-subword-navigation
code --install-extension sdras.night-owl
code --install-extension tomoki1207.vscode-input-sequence
code --install-extension wmaurer.change-case
code --install-extension yzhang.markdown-all-in-one